// Image path constants - auto-generated by CLI
export type ImagePaths = {
  lightMode: string;
  darkMode: string;
};

// Firebase Storage URLs
export const baseImgUrl = 'https://firebasestorage.googleapis.com/v0/b/crypto-images';
export const baseImgUrlToken = (nameToken: string) => `${baseImgUrl}-token/o/${nameToken}.png?alt=media`;
export const baseImgUrlSystem = (nameSystem: string) => `${baseImgUrl}-system/o/${nameSystem}.png?alt=media`;
export const baseImgUrlWallet = (nameWallet: string) => `${baseImgUrl}-wallet/o/${nameWallet}.png?alt=media`;

// Icon name mapping - auto-generated by CLI
export const iconMap: Record<string, ImagePaths> = {
  // Token icons will be added here
  "ETH": {
    lightMode: baseImgUrlToken("ETH"),
    darkMode: baseImgUrlToken("ETH")
  },
  "SOL": {
    lightMode: baseImgUrlToken("SOL-lightmode"),
    darkMode: baseImgUrlToken("SOL-darkmode")
  },
  "USDC": {
    lightMode: baseImgUrlToken("USDC"),
    darkMode: baseImgUrlToken("USDC")
  },
  "USDT": {
    lightMode: baseImgUrlToken("USDT"),
    darkMode: baseImgUrlToken("USDT")
  },

  // Wallet icons will be added here
  "Leap": {
    lightMode: baseImgUrlWallet("Leap"),
    darkMode: baseImgUrlWallet("Leap")
  },
  "MetaMask": {
    lightMode: baseImgUrlWallet("MetaMask"),
    darkMode: baseImgUrlWallet("MetaMask")
  },
  "Phantom": {
    lightMode: baseImgUrlWallet("Phantom"),
    darkMode: baseImgUrlWallet("Phantom")
  },
  "Solflare": {
    lightMode: baseImgUrlWallet("Solflare"),
    darkMode: baseImgUrlWallet("Solflare")
  },
  "WalletConnect": {
    lightMode: baseImgUrlWallet("WalletConnect"),
    darkMode: baseImgUrlWallet("WalletConnect")
  },

  // System icons will be added here
  "Solana": {
    lightMode: baseImgUrlSystem("Solana"),
    darkMode: baseImgUrlSystem("Solana")
  }
};

// Helper function to get icon paths by name
export function getIconPaths(name: string): ImagePaths | null {
  return iconMap[name] || null;
}
